=== reverse-squared/robotic-scout-magic/form-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$comment": "WSM Form Format",
    "title": "Form",
    "properties": {
        "id": {
            "type": "string",
            "description": "Identifier, should be the filename without `.json`"
        },
        "name": {
            "type": "string",
            "description": "Display Name"
        },
        "description": {
            "type": "string",
            "description": "Short description displayed on the main page"
        },
        "icon": {
            "description": "Icon to display on the main page",
            "$ref": "./icon-schema.json"
        },
        "hidden": {
            "type": "boolean",
            "description": "If true, it will be hidden from the main page."
        },
        "items": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": ["label", "text", "number", "counter", "boolean","header","radio","checkbox","text-area","date","dropdown","time","link"],
                        "description": "Sets the form component that this item uses. Required for all form elements."
                    },
                    "label": {
                        "type": "string",
                        "description": "The display text explaining what this form item is. Required for all form elements."
                    }
                },
                "required": [
                    "label", "type"
                ],
                "anyOf": [
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "not": {
                                        "enum": ["header"]
                                    }
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "exportLabel": {
                                    "type": "string",
                                    "description": "A short description which will be used when the form is exported or viewed in a table."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "text"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "helperText": {
                                    "type": "string",
                                    "description": "Extra text below the input element to help the user type the right data in."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "link"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "required": ["link"],
                            "properties": {
                                "link": {
                                    "type": "string",
                                    "description": "Link to open when the link is clicked."
                                },
                                "linkText": {
                                    "type": "string",
                                    "description": "Text to display for link"
                                },
                                "openInNewTab": {
                                    "type":"boolean",
                                    "description": "If true, the link will open in a new tab."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "number"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "helperText": {
                                    "type": "string",
                                    "description": "Extra text below the input element to help the user type the right data in."
                                },
                                "errorText": {
                                    "type": "string",
                                    "description": "Extra text below the input element when you type a non number. Defaults to 'You can only enter numbers'"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "counter"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "min": {
                                    "type": ["number", "null"],
                                    "description": "Minimum value this counter goes to, null to disable. Defaults to 0"
                                },
                                "max": {
                                    "type": ["number", "null"],
                                    "description": "Maximum value this counter goes to, null to disable. Defaults to 0"
                                },
                                "step": {
                                    "type": "number",
                                    "description": "The amount the + and - buttons change the value by. Defaults to 1"
                                },
                                "default": {
                                    "type": "number",
                                    "description": "The starting number of this counter. Defaults to 0"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "boolean"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "default": {
                                    "type": "boolean",
                                    "description": "Override the default value, default false."
                                },
                                "trueValue": {
                                    "type": "string",
                                    "description": "Change the label of the true button, default 'True'"
                                },
                                "falseValue": {
                                    "type": "string",
                                    "description": "Change the label of the false button, default 'False'"
                                },
                                "trueColor": {
                                    "type": "string",
                                    "description": "HEX color of the true button when chosen, default shade of green."
                                },
                                "falseColor": {
                                    "type": "string",
                                    "description": "HEX color of the false button when chosen, default a shade of red."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "header"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "description": {
                                    "type": "string",
                                    "description": "The text below the header. Commonly used to describe the section."
                                }
                            }
                        }
                    }, 
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "radio"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "options": {
                                    "type": "array",
                                    "description": "An array of strings representing each possible selection."
                                },
                                "default": {
                                    "type": "integer",
                                    "description": "The index of the default selected radio input. (Default: None)"
                                }
                                
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "checkbox"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "default": {
                                    "type": "boolean",
                                    "description": "Determines whether or not the checkbox should start checked."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "text-area"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "helperText": {
                                    "type": "string",
                                    "description": "The text to display below the textbox to help users know what to enter."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "dropdown"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "options": {
                                    "type": "array",
                                    "description": "An array of strings representing each possible selection."
                                },
                                "default": {
                                    "type": "integer",
                                    "description": "The index of the default selected dropdown input. (Default: None)"
                                }
                                
                            }
                        }
                    }
                ]
            },
            "description": "List of form elements for this form."
        }
    },
    "required": [ "id", "name", "items"]
}

=== reverse-squared/robotic-scout-magic/forms/2022.json
{
    "$schema": "../form-schema.json",
    "id": "2022",
    "icon": "plug",
    "name": "2022 Rapid React",
    "hidden": true,
    "description": "Click here to open scouting form",
    "items": [
        {
            "type": "number",
            "label": "The Team / Robot Number",
            "exportLabel": "Team Number"
        },
        {
            "type": "header",
            "label": "Autonomus Period"
        },
        {
            "type": "counter",
            "label": "How many lower hub cargo were scored during the autonomous period",
            "exportLabel": "Lower hub cargo during autonomous"
        },
        {
            "type": "counter",
            "label": "How many upper hub cargo were scored during the autonomous period",
            "exportLabel": "Upped hub cargo during autonomous"
        },
        {
            "type": "header",
            "label": "Teleop Period"
        },
        {
            "type": "counter",
            "label": "How many lower hub cargo were scored",
            "exportLabel": "Lower hub cargo during teleop"
        },
        {
            "type": "counter",
            "label": "How many upper hub cargo were scored",
            "exportLabel": "Upper hub cargo during teleop"
        },
        {
            "type": "number",
            "label": "Driver rating",
            "helperText": "How good are the drivers, 1 being the worst (jerky, slow to respond, always in the way), 10 being the best (smooth, aware of the field, can avoid defense)",
            "exportLabel": "Driving"
        },
        {
            "type": "header",
            "label": "End Game"
        },
        {
            "type": "radio",
            "label": "How does the robot climb",
            "options": ["First Bar", "Second Bar", "Third Bar", "Fourth Bar"],
            "exportLabel": "Climb"
        },
        {
            "type": "text-area",
            "label": "Other notes.",
            "helperText": "Anything else the robot did or has. How consistently do the cargo shot stay in the hub? Did it defend well? Was the transition from Autonomus to Teleop fast?",
            "exportLabel": "Notes"
        }
    ]
}

=== reverse-squared/robotic-scout-magic/forms/2020.json
{
    "$schema": "../form-schema.json",
    "id": "2020",
    "icon": "plug",
    "name": "2020 Infinite Recharge",
    "hidden": true,
    "description": "Click here to open scouting form",
    "items": [
        {
            "type": "number",
            "label": "The Team / Robot Number",
            "exportLabel": "Team Number"
        },
        {
            "type": "header",
            "label": "Autonomus Period"
        },
        {
            "type": "counter",
            "label": "How many level 1 balls were scored during the autonomous period",
            "exportLabel": "Level 1 balls during autonomous"
        },
        {
            "type": "counter",
            "label": "How many level 2 balls were scored during the autonomous period",
            "exportLabel": "Level 2 balls during autonomous"
        },
        {
            "type": "counter",
            "label": "How many level 3 balls were scored during the autonomous period",
            "exportLabel": "Level 3 balls during autonomous"
        },
        {
            "type": "header",
            "label": "Teleop Period"
        },
        {
            "type": "counter",
            "label": "How many level 1 balls were scored",
            "exportLabel": "Level 1 balls during teleop"
        },
        {
            "type": "counter",
            "label": "How many level 2 balls were scored",
            "exportLabel": "Level 2 balls during teleop"
        },
        {
            "type": "counter",
            "label": "How many level 3 balls were scored",
            "exportLabel": "Level 3 balls during teleop"
        },
        {
            "type": "boolean",
            "label": "Does the robot go through the trench",
            "exportLabel": "Lowbot"
        },
        {
            "type": "boolean",
            "label": "Does the robot spin the control panel",
            "exportLabel": "Control panel"
        },
        {
            "type": "number",
            "label": "Driver rating",
            "helperText": "How good are the drivers, 1 being the worst (jerky, slow to respond, always in the way), 10 being the best (smooth, aware of the field, can avoid defense)",
            "exportLabel": "Driving"
        },
        {
            "type": "header",
            "label": "End Game"
        },
        {
            "type": "radio",
            "label": "How does the robot climb",
            "options": ["It was not in the climb area", "It was on the floor of the climb area", "It climbed onto the bar when it was level", "It climbed onto the bar when it was angled"],
            "exportLabel": "Climb"
        },
        {
            "type": "boolean",
            "label": "Was the climb bar balanced at the end of the game",
            "exportLabel": "Balanced climb bar"
        },
        {
            "type": "text-area",
            "label": "Other notes.",
            "helperText": "Anything else the robot did or has. Can it lift multiple robots? Did it defend well? Was the transition from Autonomus to Teleop fast?",
            "exportLabel": "Notes"
        }
    ]
}

=== reverse-squared/robotic-scout-magic/forms/example.json
{
    "$schema": "../form-schema.json",
    "hidden": true,
    "id": "example",
    "name": "Example Form",
    "description": "Starter Example Form",
    "items": [
        {
            "type": "header",
            "label": "Text Fields"
        },
        {
            "type": "text",
            "label": "Default"
        },
        {
            "type": "text",
            "label": "With Helper Text",
            "helperText": "Enter whatever!"
        },


        {
            "type": "header",
            "label": "Number Text Fields"
        },
        {
            "type": "number",
            "label": "Default"
        },
        {
            "type": "number",
            "label": "With Helper Text",
            "helperText": "Enter whatever!"
        },
        {
            "type": "number",
            "label": "With Error Text",
            "helperText": "Enter whatever!",
            "errorText": "That is not a number!"
        },


        {
            "type": "header",
            "label": "Booleans (Yes/No boxes)"
        },
        {
            "type": "boolean",
            "label": "Default"
        },
        {
            "type": "boolean",
            "label": "True Default",
            "default": true
        },
        {
            "type": "boolean",
            "label": "False Default",
            "default": false
        },
        {
            "type": "boolean",
            "label": "Different Labels and Colors",
            "trueValue": "Purple",
            "falseValue": "Green",

            "trueColor": "purple",
            "falseColor": "green"
        },

        {
            "type": "header",
            "label": "Counters"
        },
        {
            "type": "counter",
            "label": "Default Counter"
        },
        {
            "type": "counter",
            "label": "Minimum and Maximum (0-10)",
            "min": 0,
            "max": 10
        },
        {
            "type": "counter",
            "label": "Starting Value",
            "min": 0,
            "max": 10,
            "default": 5
        },
        {
            "type": "counter",
            "label": "Step by 5",
            "min": 0,
            "max": 100,
            "default": 50,
            "step": 5
        },
        {
            "type": "counter",
            "label": "No minimum value (min: null)",
            "min": null
        },

        {
            "type": "header",
            "label": "Checkboxes"
        },
        {
            "type": "radio",
            "label": "Default",
            "options": [
                "A",
                "B",
                "C"
            ]
        },
        {
            "type": "radio",
            "label": "Default Value",
            "options": [
                "A",
                "B",
                "C"
            ],
            "default": 1
        },

        {
            "type": "header",
            "label": "Checkboxes"
        },
        {
            "type": "checkbox",
            "label": "This is a checkbox"
        },
        {
            "type": "checkbox",
            "label": "This is another checkbox"
        },
        {
            "type": "checkbox",
            "label": "This one is default selected",
            "default": true
        },
        
        {
            "type": "header",
            "label": "Text Areas",
            "description": "Same as Text Field, but with more than one line"
        },
        {
            "type": "text-area",
            "label": "Default"
        },
        {
            "type": "text-area",
            "label": "With Helper Text",
            "helperText": "Make sure to use the multiple lines with the Enter button."
        },

        {
            "type": "header",
            "label": "Date"
        },
        {
            "type": "date",
            "label": "Select the Date"
        },

        {
            "type": "header",
            "label": "Dropdowns"
        },
        {
            "type": "dropdown",
            "label": "Select your favorite letter.",
            "options": [
                "A",
                "B",
                "C"
            ]
        },

        {
            "type": "header",
            "label": "Time"
        },
        {
            "type": "time",
            "label": "Select the Time"
        }

    ]
}

=== reverse-squared/robotic-scout-magic/forms/2024.json
{
    "$schema": "../form-schema.json",
    "id": "2024",
    "icon": "itunes-note",
    "name": "2024 Crescendo",
    "hidden": true,
    "description": "Click here to open scouting form",
    "items": [
        {
            "type": "header",
            "label": "Scouter/Match Info"
        },
        {
            "type": "text",
            "label": "Student Name",
            "exportLabel": "Student Name"
        },
        {
            "type": "number",
            "label": "The Team / Robot Number",
            "exportLabel": "Team Number"
        },
        {
            "type": "number",
            "label": "Match Number",
            "exportLabel": "Match Number"
        },
        {
            "type": "header",
            "label": "Robot Position (from scoring table)"
        },
        {
            "type": "checkbox",
            "label": "Red Closest",
            "exportLabel": "Robot Position R1"
        },
        {
            "type": "checkbox",
            "label": "Red Middle",
            "exportLabel": "Robot Position R2"
        },
        {
            "type": "checkbox",
            "label": "Red Furthest",
            "exportLabel": "Robot Position R3"
        },
        {
            "type": "checkbox",
            "label": "Blue Furthest",
            "exportLabel": "Robot Position B1"
        },
        {
            "type": "checkbox",
            "label": "Blue Middle",
            "exportLabel": "Robot Position B2"
        },
        {
            "type": "checkbox",
            "label": "Blue Closest",
            "exportLabel": "Robot Position B3"
        },
        {
            "type": "header",
            "label": "Autonomous Period"
        },
        {
            "type": "boolean",
            "label": "Robot moves during autonomous",
            "exportLabel": "Auto movement",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "boolean",
            "label": "Robot picks up a Note from the ground",
            "exportLabel": "Auto ground pickup",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "boolean",
            "label": "Robot picks up a Note from the center line",
            "exportLabel": "Auto center line pickup",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "counter",
            "label": "Notes scored into the Speaker during autonomous",
            "exportLabel": "Speaker Notes during autonomous"
        },
        {
            "type": "counter",
            "label": "Notes scored into the Amp during autonomous",
            "exportLabel": "Amp Notes during autonomous"
        },
        {
            "type": "header",
            "label": "Teleop Period"
        },
        {
            "type": "checkbox",
            "label": "Does the robot pick up Notes from the ground?",
            "exportLabel": "Ground pickup",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "checkbox",
            "label": "Does the robot pick up Notes from the Source?",
            "exportLabel": "Source pickup",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "counter",
            "label": "How many Notes were scored into the Speaker",
            "exportLabel": "Speaker Notes during teleop"
        },
        {
            "type": "counter",
            "label": "How many Notes were scored into the Amp",
            "exportLabel": "Amp Notes during teleop"
        },
        {
            "type": "header",
            "label": "End Game"
        },
        {
            "type": "boolean",
            "label": "Spotlight",
            "exportLabel": "Spotlight",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "boolean",
            "label": "Trap",
            "exportLabel": "Trap",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "header",
            "label": "Climb"
        },
        {
            "type": "boolean",
            "label": "Parked",
            "exportLabel": "Parked",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "boolean",
            "label": "On Stage",
            "exportLabel": "On Stage",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "boolean",
            "label": "Harmony",
            "exportLabel": "Harmony",
            "trueValue": "TRUE",
            "falseValue": "FALSE"
        },
        {
            "type": "radio",
            "label": "Driver rating 1 being worst, 5 being the best",
            "exportLabel": "Driver rating",
            "options": [
                "1",
                "2",
                "3",
                "4",
                "5"
            ]
        },
        {
            "type": "text-area",
            "label": "Other notes.",
            "exportLabel": "Notes"
        }
    ]
}
