=== reverse-squared/robotic-scout-magic/form-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$comment": "WSM Form Format",
    "title": "Form",
    "properties": {
        "id": {
            "type": "string",
            "description": "Identifier, should be the filename without `.json`"
        },
        "name": {
            "type": "string",
            "description": "Display Name"
        },
        "description": {
            "type": "string",
            "description": "Short description displayed on the main page"
        },
        "icon": {
            "description": "Icon to display on the main page",
            "$ref": "./icon-schema.json"
        },
        "hidden": {
            "type": "boolean",
            "description": "If true, it will be hidden from the main page."
        },
        "items": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": ["label", "text", "number", "counter", "boolean","header","radio","checkbox","text-area","date","dropdown","time","link"],
                        "description": "Sets the form component that this item uses. Required for all form elements."
                    },
                    "label": {
                        "type": "string",
                        "description": "The display text explaining what this form item is. Required for all form elements."
                    }
                },
                "required": [
                    "label", "type"
                ],
                "anyOf": [
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "not": {
                                        "enum": ["header"]
                                    }
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "exportLabel": {
                                    "type": "string",
                                    "description": "A short description which will be used when the form is exported or viewed in a table."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "text"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "helperText": {
                                    "type": "string",
                                    "description": "Extra text below the input element to help the user type the right data in."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "link"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "required": ["link"],
                            "properties": {
                                "link": {
                                    "type": "string",
                                    "description": "Link to open when the link is clicked."
                                },
                                "linkText": {
                                    "type": "string",
                                    "description": "Text to display for link"
                                },
                                "openInNewTab": {
                                    "type":"boolean",
                                    "description": "If true, the link will open in a new tab."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "number"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "helperText": {
                                    "type": "string",
                                    "description": "Extra text below the input element to help the user type the right data in."
                                },
                                "errorText": {
                                    "type": "string",
                                    "description": "Extra text below the input element when you type a non number. Defaults to 'You can only enter numbers'"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "counter"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "min": {
                                    "type": ["number", "null"],
                                    "description": "Minimum value this counter goes to, null to disable. Defaults to 0"
                                },
                                "max": {
                                    "type": ["number", "null"],
                                    "description": "Maximum value this counter goes to, null to disable. Defaults to 0"
                                },
                                "step": {
                                    "type": "number",
                                    "description": "The amount the + and - buttons change the value by. Defaults to 1"
                                },
                                "default": {
                                    "type": "number",
                                    "description": "The starting number of this counter. Defaults to 0"
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "boolean"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "default": {
                                    "type": "boolean",
                                    "description": "Override the default value, default false."
                                },
                                "trueValue": {
                                    "type": "string",
                                    "description": "Change the label of the true button, default 'True'"
                                },
                                "falseValue": {
                                    "type": "string",
                                    "description": "Change the label of the false button, default 'False'"
                                },
                                "trueColor": {
                                    "type": "string",
                                    "description": "HEX color of the true button when chosen, default shade of green."
                                },
                                "falseColor": {
                                    "type": "string",
                                    "description": "HEX color of the false button when chosen, default a shade of red."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "header"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "description": {
                                    "type": "string",
                                    "description": "The text below the header. Commonly used to describe the section."
                                }
                            }
                        }
                    }, 
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "radio"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "options": {
                                    "type": "array",
                                    "description": "An array of strings representing each possible selection."
                                },
                                "default": {
                                    "type": "integer",
                                    "description": "The index of the default selected radio input. (Default: None)"
                                }
                                
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "checkbox"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "default": {
                                    "type": "boolean",
                                    "description": "Determines whether or not the checkbox should start checked."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "text-area"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "helperText": {
                                    "type": "string",
                                    "description": "The text to display below the textbox to help users know what to enter."
                                }
                            }
                        }
                    },
                    {
                        "if": {
                            "properties": {
                                "type": {
                                    "enum": [
                                        "dropdown"
                                    ]
                                }
                            }
                        },
                        "then": {
                            "properties": {
                                "options": {
                                    "type": "array",
                                    "description": "An array of strings representing each possible selection."
                                },
                                "default": {
                                    "type": "integer",
                                    "description": "The index of the default selected dropdown input. (Default: None)"
                                }
                                
                            }
                        }
                    }
                ]
            },
            "description": "List of form elements for this form."
        }
    },
    "required": [ "id", "name", "items"]
}

=== reverse-squared/robotic-scout-magic/forms/pits.json
{
    "$schema": "../form-schema.json",
    "id": "pits",
    "icon": "plug",
    "name": "Pit Scouting",
    "hidden": false,
    "description": "Click here to open scouting form",
    "items": [
        {
            "type": "number",
            "label": "The Team / Robot Number",
            "exportLabel": "Team Number"
        },
        {
            "type": "link",
            "link": "https://drive.google.com/drive/folders/1Lbi5TeLe1w2A8UoeiFunt2Pz8VWX7LA0?usp=sharing",
            "linkText": "Google Drive",
            "label": "Upload Picture Here",
            "openInNewTab": true
        },
        {
            "type": "header",
            "label": "Robot Information"
        },
        {
            "type": "radio",
            "label": "Where can the robot score",
            "options": [
                "Speaker only",
                "Amp only",
                "Both"
            ],
            "exportLabel": "Shooter"
        },
        {
            "type": "radio",
            "label": "What kind of climber does the robot have",
            "options": [
                "Climber in a box (or similar)",
                "Buddy climb",
                "Other",
                "None"
            ],
            "exportLabel": "Climb"
        },
        {
            "type": "boolean",
            "label": "Do you have a ground pick up?",
            "exportLabel": "Ground Pick Up"
        },
        {
            "type": "boolean",
            "label": "Can you pick up from the source?",
            "exportLabel": "Pick Up from Source"
        },
        {
            "type": "number",
            "label": "What is your average number of cycles?",
            "exportLabel": "Average Cycles"
        },
        {
            "type": "number",
            "label": "What is your robot height?",
            "exportLabel": "Robot Height"
        },
        {
            "type": "number",
            "label": "What is your robot weight?",
            "exportLabel": "Robot Weight"
        },
        {
            "type": "boolean",
            "label": "Can you score in the amp?",
            "exportLabel": "Score in Amp"
        },
        {
            "type": "boolean",
            "label": "Can you climb the chain?",
            "exportLabel": "Climb Chain"
        },
        {
            "type": "boolean",
            "label": "Can you complete a harmony?",
            "exportLabel": "Complete Harmony"
        },
        {
            "type": "boolean",
            "label": "Can you score in the trap?",
            "exportLabel": "Score in Trap"
        },
        {
            "type": "boolean",
            "label": "Can you score in the speaker?",
            "exportLabel": "Score in Speaker"
        },
        {
            "type": "radio",
            "label": "What is your drive train?",
            "options": [
                "Tank drive",
                "Swerve drive",
                "Mecanum drive",
                "Other"
            ],
            "exportLabel": "Drive Train"
        },
        {
            "type": "text-area",
            "label": "Other notes.",
            "helperText": "",
            "exportLabel": "Notes"
        }
    ]
}

=== reverse-squared/robotic-scout-magic/forms/2018.json
{
    "$schema": "../form-schema.json",
    "icon": "arrow-up",
    "id": "2018",
    "name": "2018 FIRST Power Up",
    "hidden": true,
    "description": "A scouting form for 2018's FIRST Power Up Game",
    "items": [
        {
            "type": "number",
            "label": "The Team / Robot Number",
            "exportLabel": "Team Number"
        },
        {
            "type": "header",
            "label": "Autonomous Period"
        },
        {
            "type": "boolean",
            "label": "Did the robot cross the auto line?",
            "trueValue": "Yes",
            "falseValue": "No",
            "default": false
        },
        {
            "type": "counter",
            "label": "How many cubes were scored on the scale during the autonomous period?",
            "exportLabel": "Scale Cubes Scored in Auton"
        },
        {
            "type": "counter",
            "label": "How many cubes were scored on the switch during the autonomous period?",
            "exportLabel": "Switc Cubes Scored in Auton"
        },
        {
            "type": "header",
            "label": "Teleop Period"
        },
        {
            "type": "counter",
            "label": "How many cubes were scored on the scale?",
            "exportLabel": "Scale Cubes Scored"
        },
        {
            "type": "counter",
            "label": "How many cubes were scored on the switch?",
            "exportLabel": "Switch Cubes Scored"
        },
        {
            "type": "counter",
            "label": "How many cubes were scored in the exchange?",
            "exportLabel": "Exchange Cubes Scored"
        },
        {
            "type": "header",
            "label": "End Game"
        },
        {
            "type": "radio",
            "label": "What did the robot do at the end of the match?",
            "options": [
                "The robot climbed.",
                "The robot ended on the mat.",
                "The robot didn't climb or end on the mat."
            ],
            "exportLabel": "Where Was the Robot At the End?"
        },
        {
            "type": "text-area",
            "label": "Other notes.",
            "exportLabel": "Notes"
        }
    ]
}

=== reverse-squared/robotic-scout-magic/forms/2019.json
{
    "$schema": "../form-schema.json",
    "id": "2019",
    "icon": "space-shuttle",
    "name": "2019 Destination: Deep Space",
    "hidden": true,
    "description": "Blast off with scouting with this form.",
    "items": [
        {
            "type": "number",
            "label": "The Team / Robot Number",
            "exportLabel": "Team Number"
        },
        {
            "type": "header",
            "label": "Sandstorm Period"
        },
        {
            "type": "radio",
            "label": "What game piece did the robot start with?",
            "options": [
                "Hatch Panel",
                "Cargo"
            ],
            "exportLabel": "Starting Game Piece"
        },
        {
            "type": "boolean",
            "label": "Did the robot leave the HAB?",
            "default": false,
            "exportLabel": "Left HAB During Sandstorm?"
        },
        {
            "type": "counter",
            "label": "How many Hatch Panels were scored during the sandstorm period?",
            "exportLabel": "Hatch Panels Scored in Sandstorm"
        },
        {
            "type": "counter",
            "label": "How much Cargo was scored during the sandstorm period?",
            "exportLabel": "Cargo Stored in Sandstorm"
        },
        {
            "type": "header",
            "label": "Teleop Period"
        },
        {
            "type": "counter",
            "label": "How many Hatch Panels were scored?",
            "exportLabel": "Hatch Panels Scored"
        },
        {
            "type": "counter",
            "label": "How much Cargo was scored?",
            "exportLabel": "Cargo Scored"
        },
        {
            "type": "boolean",
            "label": "Can the robot pick hatch panels off the ground?",
            "exportLabel": "Can Pick Hatch Panels Off Ground?"
        },
        {
            "type": "header",
            "label": "End Game"
        },
        {
            "type": "radio",
            "label": "What level did the robot climb to at the end of the match?",
            "options": ["0 (Wasn't in the HAB)", "1", "2", "3"],
            "exportLabel": "Level Climbed"
        },
        {
            "type": "boolean",
            "label": "Can the robot even climb to level three. If you are not sure, select No.",
            "exportLabel": "Could the Robot Climb to Level 3?"
        },
        {
            "type": "text-area",
            "label": "Other notes.",
            "helperText": "Anything else the robot did or has. Did it have a ramp? Did it defend well? Was the transition from the Sandstorm to Teleop fast?",
            "exportLabel": "Notes"
        }
    ]
}
